---

name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  flatpak:
    name: Flatpak (${{ matrix.configuration.name }})
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6
      options: --privileged

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - name: x86
            platform: false
            architecture: x86_64

          - name: ARM
            platform: arm64
            architecture: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Docker
        if: ${{ matrix.configuration.platform }}
        run: |
         apt update
         apt install -y docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ matrix.configuration.platform }}
        with:
          platforms: ${{ matrix.configuration.platform }}

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: calculator.flatpak
          manifest-path: io.elementary.calculator.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          arch: ${{ matrix.configuration.architecture }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: io.elementary.vala-lint -d .
