---

name: Release

on:
  pull_request:
    branches: master
    types: closed

jobs:
  create_release:
     name: Create Release
     runs-on: ubuntu-latest

     if: github.event.pull_request.merged == true && true == contains(join(github.event.pull_request.labels.*.name), 'Release')

     steps:
       - name: Checkout
         uses: actions/checkout@v1
       
       - name: Release
         uses: elementary/actions/release@master
         env:
           GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
           GIT_USER_NAME: "elementaryBot"
           GIT_USER_EMAIL: "builds@elementary.io"
         with:
           release_branch: 'odin'

  deploy_flatpak:
    name: Deploy Flatpak (${{ matrix.configuration.name }})
    runs-on: ubuntu-latest
    
    if: github.event.pull_request.merged == true && true == contains(join(github.event.pull_request.labels.*.name), 'Release')

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:6
      options: --privileged

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - name: x86
            platform: false
            architecture: x86_64

          - name: ARM
            platform: arm64
            architecture: aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Docker
        if: ${{ matrix.configuration.platform }}
        run: |
         dnf install -y docker

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: ${{ matrix.configuration.platform }}
        with:
          platforms: ${{ matrix.configuration.platform }}

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: calculator.flatpak
          manifest-path: io.elementary.calculator.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          branch: stable
          arch: ${{ matrix.configuration.architecture }}

  
      - name: Deploy
        uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3
        with:
          repository: appcenter
          flat-manager-url: https://flatpak-api.elementary.io
          token: ${{ secrets.FLAT_MANAGER_TOKEN }}
